apiVersion: apps/v1
kind: Deployment
metadata:
  name: tingeso2proveedor
  labels:
    app: tingeso2proveedor
spec:
  selector:
    matchLabels:
      app: tingeso2proveedor
  template:
    metadata:
      labels:
        app: tingeso2proveedor
    spec:
      containers:
      - name: tingeso2proveedor
        image: postgres:latest
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: "1234"
        - name: POSTGRES_DB
          value: "proveedor"
        volumeMounts:
        - name: tingeso2proveedor-persistent-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: tingeso2proveedor-persistent-storage
        persistentVolumeClaim:
          claimName: tingeso2proveedor-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tingeso2proveedor-pv-claim
  labels:
    app: tingeso2proveedor
    tier: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Mi
---
apiVersion: v1
kind: Service
metadata:
  name: tingeso2proveedor
  labels:
    app: tingeso2proveedor
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: tingeso2proveedor
  clusterIP: None
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: proveedor-db
data:
  name: "proveedor"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tingeso2llegada
  labels:
    app: tingeso2llegada
spec:
  selector:
    matchLabels:
      app: tingeso2llegada
  template:
    metadata:
      labels:
        app: tingeso2llegada
    spec:
      containers:
      - name: tingeso2llegada
        image: postgres:latest
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: "1234"
        - name: POSTGRES_DB
          value: "llegada"
        volumeMounts:
        - name: tingeso2llegada-persistent-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: tingeso2llegada-persistent-storage
        persistentVolumeClaim:
          claimName: tingeso2llegada-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tingeso2llegada-pv-claim
  labels:
    app: tingeso2llegada
    tier: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Mi
---
apiVersion: v1
kind: Service
metadata:
  name: tingeso2llegada
  labels:
    app: tingeso2llegada
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: tingeso2llegada
  clusterIP: None
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: llegada-db
data:
  name: "llegada"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tingeso2resultado
  labels:
    app: tingeso2resultado
spec:
  selector:
    matchLabels:
      app: tingeso2resultado
  template:
    metadata:
      labels:
        app: tingeso2resultado
    spec:
      containers:
      - name: tingeso2resultado
        image: postgres:latest
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: "1234"
        - name: POSTGRES_DB
          value: "resultado"
        volumeMounts:
        - name: tingeso2resultado-persistent-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: tingeso2resultado-persistent-storage
        persistentVolumeClaim:
          claimName: tingeso2resultado-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tingeso2resultado-pv-claim
  labels:
    app: tingeso2resultado
    tier: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Mi
---
apiVersion: v1
kind: Service
metadata:
  name: tingeso2resultado
  labels:
    app: tingeso2resultado
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: tingeso2resultado
  clusterIP: None
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: resultado-db
data:
  name: "resultado"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tingeso2pago
  labels:
    app: tingeso2pago
spec:
  selector:
    matchLabels:
      app: tingeso2pago
  template:
    metadata:
      labels:
        app: tingeso2pago
    spec:
      containers:
      - name: tingeso2pago
        image: postgres:latest
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: "1234"
        - name: POSTGRES_DB
          value: "pago"
        volumeMounts:
        - name: tingeso2pago-persistent-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: tingeso2pago-persistent-storage
        persistentVolumeClaim:
          claimName: tingeso2pago-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tingeso2pago-pv-claim
  labels:
    app: tingeso2pago
    tier: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Mi
---
apiVersion: v1
kind: Service
metadata:
  name: tingeso2pago
  labels:
    app: tingeso2pago
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: tingeso2pago
  clusterIP: None
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pago-db
data:
  name: "pago"