apiVersion: apps/v1
kind: Deployment
metadata:
  name: tingeso2proveedor
  labels:
    app: tingeso2proveedor
spec:
  selector:
    matchLabels:
      app: tingeso2proveedor
  template:
    metadata:
      labels:
        app: tingeso2proveedor
    spec:
      containers:
      - name: tingeso2proveedor
        image: postgres:latest
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: "1234"
        - name: POSTGRES_DB
          value: "proveedor"
        volumeMounts:
        - name: tingeso2proveedor-persistent-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: tingeso2proveedor-persistent-storage
        persistentVolumeClaim:
          claimName: tingeso2proveedor-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tingeso2proveedor-pv-claim
  labels:
    app: tingeso2proveedor
    tier: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Mi
---
apiVersion: v1
kind: Service
metadata:
  name: tingeso2proveedor
  labels:
    app: tingeso2proveedor
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: tingeso2proveedor
  clusterIP: None
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: proveedor-db
data:
  name: "proveedor"
