apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-service
  labels:
    app: config-service
spec:
  selector:
    matchLabels:
      app: config-service
  replicas: 1
  template:
    metadata:
      labels:
        app: config-service
    spec:
      containers:
      - name: config-service
        image: cristowo/tingeso2config:latest
        ports:
        - containerPort: 8081

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-service
  labels:
    app: eureka-service
spec:
  selector:
    matchLabels:
      app: eureka-service
  replicas: 1
  template:
    metadata:
      labels:
        app: eureka-service
    spec:
      containers:
      - name: eureka-service
        image: cristowo/tingeso2eureka:latest
        env:
        - name: status.podIP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        ports:
        - containerPort: 8761

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proveedor-service
  labels:
    app: proveedor-service
spec:
  selector:
    matchLabels:
      app: proveedor-service
  replicas: 1
  template:
    metadata:
      labels:
        app: proveedor-service
    spec:
      containers:
      - name: proveedor-service
        image: cristowo/tingeso2proveedor:latest
        ports:
        - containerPort: 8082
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://tingeso2proveedor:5432/postgres
        - name: SPRING_DATASOURCE_USERNAME
          value: postgres
        - name: SPRING_DATASOURCE_PASSWORD
          value: "1234"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
  labels:
    app: gateway-service
spec:
  selector:
    matchLabels:
      app: gateway-service
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
      - name: gateway-service
        image: cristowo/tingeso2gateway:latest
        ports:
        - containerPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontened-service
  labels:
    app: frontened-service
spec:
  selector:
    matchLabels:
      app: frontened-service
  replicas: 1
  template:
    metadata:
      labels:
        app: frontened-service
    spec:
      containers:
      - name: frontened-service
        image: cristowo/tingeso2frontend:latest
        ports:
        - containerPort: 3000