apiVersion: v1
kind: Service
metadata:
  name: config-service
spec:
  selector:
    app: config-service
  ports:
    - nodePort: 30500
      protocol: TCP
      port: 8081
      targetPort: 8081
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: eureka-service
spec:
  selector:
    app: eureka-service
  ports:
    - nodePort: 30501
      protocol: TCP
      port: 8761
      targetPort: 8761
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: proveedor-service
spec:
  selector:
    app: proveedor-service
  ports:
    - nodePort: 30502
      protocol: TCP
      port: 8082
      targetPort: 8082
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: llegada-service
spec:
  selector:
    app: llegada-service
  ports:
    - nodePort: 30503
      protocol: TCP
      port: 8083
      targetPort: 8083
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: resultado-service
spec:
  selector:
    app: resultado-service
  ports:
    - nodePort: 30504
      protocol: TCP
      port: 8084
      targetPort: 8084
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: pago-service
spec:
  selector:
    app: pago-service
  ports:
    - nodePort: 30505
      protocol: TCP
      port: 8085
      targetPort: 8085
  type: NodePort


---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  selector:
    app: gateway-service
  ports:
    - nodePort: 30506
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
