server:
  port: 8080
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: llegada-service
          uri: lb://llegada-service
          predicates:
            - Path=/llegadas/**
        - id: proveedor-service
          uri: lb://proveedor-service
          predicates:
            - Path=/proveedores/**
        - id: resultado-service
          uri: lb://resultado-service
          predicates:
            - Path=/resultados/**
        - id: pago-service
          uri: lb://pago-service
          predicates:
            - Path=/pagos/**