server:
  port: 8080
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://eureka-service.default.svc.cluster.local:8761/eureka/
  instance:
    hostname: ${EUREKA:10.244.0.25}

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origin-patterns: '*'
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
      routes:
        - id: llegada-service
          uri: lb://llegada-service
          predicates:
            - Path=/llegadas/**
        - id: proveedor-service
          uri: lb://proveedor-service-54f4b95d88-p5bjq
          predicates:
            - Path=/proveedores/**
        - id: resultado-service
          uri: lb://resultado-service
          predicates:
            - Path=/resultados/**
        - id: pago-service
          uri: lb://pago-service
          predicates:
            - Path=/pagos/**